# Generated by Django 5.1 on 2025-04-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('pest', models.CharField(blank=True, max_length=100)),
                ('advice', models.TextField()),
                ('advisory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agro_advisories', to='advisories.advisory')),
            ],
        ),
    ]
